# Site settings
title: A Very Good Rabbit
email: pincil@163.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alenliang.github.io" # the base hostname & protocol for your site
twitter_username: Liang Yilun
github_username:  alenliang

# Build settings
markdown: kramdown
